namespace OrderService.DTOs;

// Separate from OrderDto deliberately - a client creating an order
// should NOT be able to specify Id (auto-generated by the database) or
// TotalAmount (we calculate this ourselves server-side from the items,
// rather than trusting a client-supplied number - a real business
// integrity concern, not just a style choice).
public class CreateOrderItemDto
{
    public string ProductName { get; set; } = string.Empty;
    public int Quantity { get; set; }
    public decimal UnitPrice { get; set; }
}

public class CreateOrderDto
{
    public string CustomerName { get; set; } = string.Empty;
    public List<CreateOrderItemDto> Items { get; set; } = new();
}
